# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "root_provision.sh"
  config.vm.provision "shell", path: "provision.sh", privileged: false
  # Set default shell to zsh
  config.vm.provision "shell",
    inline: "sudo chsh -s $(which zsh) vagrant"
end
